require("plugins_settings.treesitter")
require("plugins_settings.cmp")
require("plugins_settings.saga")
require("plugins_settings.devicons")
require("plugins_settings.which-key")
require("plugins_settings.ufo")
require("plugins_settings.noice")
require("plugins_settings.telescope")
require("plugins_settings.neotree")
require("plugins_settings.gitsigns")
require("plugins_settings.comment")
require("plugins_settings.smoothcursor")
require("plugins_settings.indent-blankline")
require("plugins_settings.nvim-autopairs")
require("plugins_settings.dashboard")
require("plugins_settings.bufferline")
require("plugins_settings.heirline")
require("plugins_settings.vimtex")

-- require("plugins_settings.copilot")
-- require("plugins_settings.gpt")
