local wk = require("which-key")

wk.setup({
	win = { border = "single", col = 0.5 },
	preset = "modern",
})

wk.add({
	{ "<leader>b", group = "buffer" },
	{ "<leader>bl ", "<cmd>Telescope buffers<cr>", desc = "List Buffers" },
	{ "<leader>bd", "<cmd>bdelete<cr>", desc = "Delete Buffer" },
	{ "<leader>c", group = "code" },
	{ "<leader>ca", "<cmd>Lspsaga code_action<cr>", desc = "Code Action", mode="n" },
	{ "<leader>cd", "<cmd>Lspsaga show_line_diagnostics<CR>", desc = "Code Diagnostics" },
	{ "<leader>ce", "<cmd>Telescope colorscheme<cr>", desc = "Colorscheme" },
	{ "<leader>cf", "<cmd>lua vim.lsp.buf.format({ timeout_ms = 2000 })<cr>", desc = "Format Code" },
	{ "<leader>cl", desc = "Comment Line" },
	{ "<leader>cb", desc = "Comment Block", mode = "v" },
	{ "<leader>db", "<cmd>Lspsaga show_buf_diagnostics<cr>", desc = "Diagnostics" },
	--[[
  { "<leader>e", group = "explorer" },
	{ "<leader>ee", "<cmd>Neotree float toggle reveal_force_cwd<cr>", desc = "File Explorer" },
	{ "<leader>eb", "<cmd>Neotree float toggle buffers<cr>", desc = "Buffers" },
	{ "<leader>es", "<cmd>Neotree float toggle git_status<cr>", desc = "Git Status" },
	{ "<leader>ed", "<cmd>Neotree float toggle document_symbols<cr>", desc = "Document Symbolys" },
  ]]
	{ "<leader>o", "<cmd>Lspsaga outline<cr>", desc = "Outline" },
	{ "<leader>f", group = "find" },
	{ "<leader>ff", "<cmd>Telescope find_files<cr>", desc = "Find File" },
	{ "<leader>fb", "<cmd>Telescope file_browser<cr>", desc = "File Browser" },
	{ "<leader>fg", "<cmd>Telescope live_grep<cr>", desc = "Live grep" },
	{ "<leader>fw", "<cmd>Telescope current_buffer_fuzzy_find<cr>", desc = "Current Buffer Fuzzy" },
	{ "<leader>fo", "<cmd>Telescope oldfiles<cr>", desc = "Open Recent File" },
	{ "<leader>fs", "<cmd>Lspsaga finder tyd+ref+imp+def<cr>", desc = "Find references" },
	{ "<leader>g", group = "git & lsp" },
	{ "<leader>gb", "<cmd>Telescope git_branches<cr>", desc = "Git Branches" },
	{ "<leader>gc", "<cmd>Telescope git_commits<cr>", desc = "Git Commits" },
	{ "<leader>gs", "<cmd>Telescope git_status<cr>", desc = "Git Status" },
	{ "<leader>gt", "<cmd>Lspsaga peek_type_definition<cr>", desc = "Peek type definition" },
	{ "<leader>gp", "<cmd>Lspsaga peek_definition<cr>", desc = "Peek definition" },
	{ "<leader>gd", "<cmd>Lspsaga goto_definition<cr>", desc = "Go to Definition" },
	{ "<leader>gD", desc = "Go to Declaration" },
	{ "<leader>gi", desc = "Go to Implementation" },
	{ "<leader>gI", desc = "<cmd>Gitignore<cr>" },
	{ "<leader>k", "<cmd>Lspsaga hover_doc<cr>", desc = "Hover Doc" },
	{ "<leader>q", group = "quit" },
	{ "<leader>qq", desc = "Quit current file" },
	{ "<leader>qa", desc = "Quit all" },
	{ "<leader>rn", "<cmd>Lspsaga rename<cr>", desc = "Rename" },
	{ "<leader>w", group = "save" },
	{ "<leader>ww", desc = "Save file" },
	{ "<leader>wa", desc = "Save all files" },
	{ "<leader>wq", desc = "Save all files and quit" },
	{ "<leader>v", group = "vimtex" },
	{ "<leader>vc", "<cmd>VimtexCompile<cr>", desc = "Compile" },
	{ "<leader>vv", "<cmd>VimtexView<cr>", desc = "View" },
	{ "<leader>ve", "<cmd>VimtexErrors<cr>", desc = "Errors" },
	{ "<leader>vs", "<cmd>VimtexStatus<cr>", desc = "Status" },
	{ "<leader>vt", "<cmd>VimtexStop<cr>", desc = "Stop" },
})
